# Generated by Django 4.2.7 on 2023-11-24 14:13

from django.db import migrations, models
import shop_api.enums


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0002_user_is_active_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancel', 'CANCEL'), ('waiting', 'WAITING'), ('success', 'SUCCESS')], default=shop_api.enums.StatusEnum['WAITING'], max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('represent', 'REPRESENT'), ('client', 'CLIENT')], max_length=255, verbose_name='Роль'),
        ),
    ]
