# Generated by Django 4.2.7 on 2023-11-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0003_alter_order_status_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
