# Generated by Django 4.2.7 on 2023-11-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0004_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='product',
        ),
    ]
