# Generated by Django 4.2.7 on 2023-11-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0009_specialoffer_remove_productwaitlist_quantity_need_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
